### ISSUE TITLE
Does SLAMD handle categorical variables?

### ISSUE THREAD

**Issue by sgbaird** [BAMresearch/SequentialLearningApp#2]
> In the upload dialog it is possible to set the CSV separator and the decimal separator and to delete non-numeric data.

**Comment by iterateccvoelker** [comment]
Hi Sterling,

thanks for you interest. The CSV separator can be chosen from a preset list. The decimal separator is recognized automatically. Data cleansing can be performed with the pre-set erasers. So far slamd only handles numeric data. Categorical variables must be transformed before data upload. A more advanced data pre-processing has been out of the scope of this implementation. However, we are working on a more advanced flask implementation which will have more functionalities.
Please feel free to get involved and add any missing functionality. The code should be easy to edit. Pleas feel free to reach out if you have more questions. 

I hope this answers your question. Please do not hesitate to ask if not.

best regards,

Christoph

**Comment by sgbaird** [comment]
Perfect, thanks Christoph!
